routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\LogController;

require_once 'challenge1.php';

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth:sanctum', 'verified']], function() {
    Route::resource('/tasks', TaskController::class);
    Route::get('/logs/task/{taskId}/create', [LogController::class, 'create'])->name('logs.create');
    Route::post('/logs/task/{taskId}', [LogController::class, 'store'])->name('logs.store');
});

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id', 'name', 'description', 'max_execution_date', 'active'
    ];

    /**
     * Relations
     */
    public function user() { return $this->belongsTo(User::class, 'user_id'); }
    public function logs() { return $this->hasMany(Log::class, 'task_id'); }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\ActionNotAllowedException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use App\Models\Task;
use App\Exceptions\ModelNotFoundException;
use App\Http\Requests\CreateTaskRequest;
use App\Http\Requests\EditTaskRequest;
use App\Models\StandardResponse;

class TaskController extends Controller
{

    private $standard;

    public function __construct()
    {
        $this->standard = new StandardResponse;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();

        // Handle tasks to show them
        $tasks = Task::all()->map(function($item) use($user) {
            $item->blocked = ($item->user_id != $user->id);
            return $item;
        });

        $data = [
            'tasks' => $tasks
        ];

        return view('tasks.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tasks.create'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Auth::user();
        try {

            $task =  Task::find($id);
            throw_if(empty($task), new ModelNotFoundException);
            throw_if($task->user_id != $user->id, new ActionNotAllowedException);

            $data = [
                'task'      => $task,
                'showing'   => true,
                'addLog'    => true
            ];

            return view('tasks.show', $data);

        } catch(ActionNotAllowedException $exception) {
            $this->standard->message = __('errors.action.not_allowed');
        } catch(ModelNotFoundException $exception) {
            $this->standard->message = __('errors.model.not_found');
        } catch(\Exception $exception) {
            Log::error($exception->getMessage());
        }

        return redirect()->route('tasks.index')->with('response', $this->standard);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $user = Auth::user();

        try {

            $task =  Task::find($id);
            throw_if(empty($task), new ModelNotFoundException);
            throw_if($task->user_id != $user->id, new ActionNotAllowedException);

            $data = [
                'task'      => $task,
                'addLog'    => true
            ];

            return view('tasks.edit', $data);

        } catch(ActionNotAllowedException $exception) {
            $this->standard->message = __('errors.action.not_allowed');
        } catch(ModelNotFoundException $exception) {
            $this->standard->message = __('errors.model.not_found');
        } catch(\Exception $exception) {
            Log::error($exception->getMessage());
        }

        return redirect()->route('tasks.index')->with('response', $this->standard);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTaskRequest $request)
    {
        $user = Auth::user();
    
        try {

            $data = $request->validated();
            $data['user_id'] = $user->id;

            // Create new task
            $task = Task::create($data);

            $this->standard->success = true;
            $this->standard->message = __('custom.action.ok', ['obj' => Str::title(trans_choice('custom.task', 1)), 'action' => 'created']);

            return redirect()->route('tasks.index')->with('response', $this->standard);

        } catch(\Exception $exception) {
            Log::error($exception->getMessage());
        }
        
        return back()->withInput()->with('response', $this->standard);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditTaskRequest $request, $id)
    {
        $user = Auth::user();
    
        try {

            $task = Task::find($id);
            throw_if(empty($task), new ModelNotFoundException);
            throw_if($task->user_id != $user->id, new ActionNotAllowedException);

            // Update task
            $task->update($request->validated());

            $this->standard->success = true;
            $this->standard->message = __('custom.action.ok', ['obj' => Str::title(trans_choice('custom.task', 1)), 'action' => 'updated']);

            return redirect()->route('tasks.index')->with('response', $this->standard);

        } catch(ActionNotAllowedException $exception) {
            $this->standard->message = __('errors.action.not_allowed');
        } catch(ModelNotFoundException $exception) {
            $this->standard->message = __('errors.model.not_found');
        } catch(\Exception $exception) {
            Log::error($exception->getMessage());
        }
        
        return back()->withInput()->with('response', $this->standard);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();
    
        try {

            $task = Task::find($id);
            throw_if(empty($task), new ModelNotFoundException);
            throw_if($task->user_id != $user->id, new ActionNotAllowedException);

            // Delete task
            $task->delete();

            $this->standard->success = true;
            $this->standard->message = __('custom.action.ok', ['obj' => Str::title(trans_choice('custom.task', 1)), 'action' => 'deleted']);

            return redirect()->route('tasks.index')->with('response', $this->standard);

        } catch(ActionNotAllowedException $exception) {
            $this->standard->message = __('errors.action.not_allowed');
        } catch(ModelNotFoundException $exception) {
            $this->standard->message = __('errors.model.not_found');
        } catch(\Exception $exception) {
            Log::error($exception->getMessage());
        }
        
        return back()->withInput()->with('response', $this->standard);
    }
}

resources/views/tasks/_form.blade.php
@isset($addLog)
<a href="{{ route('logs.create', $task->id) }}" class="btn btn-success text-white" role="button">+ Add log to task</a>
@endisset
<div class="form-group my-3">
    <label for="name">Name</label>
    <input type="text" class="form-control" name="name" id="name" value="{{ old('name') ?? $task->name ?? '' }}" placeholder="Task name" required @if(isset($showing)) disabled @endif />
</div>
<div class="form-group my-3">
    <label for="name">Maximum execution date</label>
    <input type="text" class="form-control" name="max_execution_date" id="max_execution_date" value="{{ old('max_execution_date') ?? $task->max_execution_date ?? '' }}" @if(isset($showing)) disabled @endif placeholder="Maximum execution date, format: yyyy-mm-dd" required />
</div>
<div class="form-group my-3">
    <label for="description">Description</label>
    <textarea class="form-control" name="description" id="description" rows="3" placeholder="Write a short description for your task" @if(isset($showing)) disabled @endif required>{{ old('description') ?? $task->description ?? '' }}</textarea>
</div>
@if(!isset($showing))
<button type="submit" class="btn btn-primary text-white">{{ $submitText }}</button>
@endif
<a href="{{ route('tasks.index') }}" role="button" class="btn btn-light">Cancel</a>

resources/views/tasks/create.blade.php
@extends('layout')
@section('title', 'Create new task')
@section('content')
<form method="post" action="{{ route('tasks.store') }}">
    @csrf
    @include('tasks._form', [
        'submitText' => 'Create task'
    ])
</form>
@endsection

resources/views/tasks/edit.blade.php
@extends('layout')
@section('title', 'Edit task')
@section('content')
<form method="post" action="{{ route('tasks.update', $task->id) }}">
    @csrf
    @method('PUT')
    @include('tasks._form', [
        'submitText' => 'Edit task'
    ])
</form>
@endsection

resources/views/tasks/index.blade.php
@extends('layout')
@section('title', 'Tasks list')
@section('content')
<a href="{{ route('tasks.create') }}" role="button" class="btn btn-success btn-lg text-white">+ Add task</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Owner</th>
            <th scope="col">Execution date</th>
            <th scope="col">Description</th>
            <th scope="col">Logs number</th>
            <th scope="col">Actions</th>
        </tr>
  </thead>
  <tbody>
        @forelse($tasks as $task)
        <tr>
            <th scope="row">{{ $task->id }}</th>
            <td>{{ $task->name }}</td>
            <td>{{ $task->user->name }} ({{ $task->user->email }})</td>
            <td>{{ $task->max_execution_date }}</td>
            <td>{{ $task->description }}</td>
            <td>{{ $task->logs->count() }}</td>
            <td style="width:20%">
                @if(!$task->blocked)
                <a href="{{ route('tasks.show', $task->id) }}" class="btn btn-primary btn-sm text-white" role="button">Show</a>
                <a href="{{ route('tasks.edit', $task->id) }}" class="btn btn-info btn-sm text-white" role="button">Edit</a>
                <form id="delete-task-{{ $task->id }}" style="display: inline-block !important" action="{{ route('tasks.destroy', $task->id) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm text-white inline-block do-delete" type="button" data-id="{{ $task->id }}">Delete</button>
                </form>
                @endif
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="7">No tasks found!</td>
        </tr>
        @endforelse
  </tbody>
</table>
@endsection
@push('scripts')
<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(e) {
        $(document).on('click', '.do-delete', function(evt) {
            const $id = $(this).data('id');
            if(confirm("Are you sure you want to delete the selected task?")){
                $('#delete-task-'+$id).submit();
            } else {
                return false;
            }
        });
    });
</script>
@endpush

resources/views/tasks/show.blade.php
@extends('layout')
@section('title', 'Show task details')
@section('content')
@include('tasks._form', [
    'submitText'    => 'Show task'
])
@endsection